CREATE VIEW CURRENT_HOLDINGS_ALL AS
SELECT
    a.ACCOUNT_ID,
    a.ACCOUNT_NAME,
	a.ACCOUNT_OWNER,
    h.ASSET_ID,
    h.VOLUME,
    s.NAME,
    s.MARKET,
    s.CATEGORY,
    s.SUB_CATEGORY,
    s.PROFILE,
    p.PRICE AS CURRENT_PRICE,
    s.CURRENCY,
    COALESCE(c.PRICE, 1) AS FX_RATE
FROM
    HOLDINGS h
LEFT JOIN
    ACCOUNTS a ON h.ACCOUNT_ID = a.ACCOUNT_ID
LEFT JOIN
    ASSETS s ON h.ASSET_ID = s.ASSET_ID
LEFT JOIN
    LATEST_PRICES p ON s.ASSET_ID = p.ASSET_ID
LEFT JOIN (
    SELECT
        c.PRICE,
        s.CURRENCY
    FROM
        LATEST_CURRENCIES c
    JOIN
        ASSETS s ON c.ASSET_ID = s.ASSET_ID
        ) c on s.CURRENCY = c.CURRENCY
WHERE
    1=1
