CREATE TABLE IF NOT EXISTS "ASSETS" (
	"ASSET_ID"	INTEGER NOT NULL,
	"NAME"	TEXT NOT NULL,
	"MARKET"	TEXT NOT NULL,
	"CATEGORY"	TEXT,
	"SUB_CATEGORY"	TEXT,
	"PROFILE"	TEXT,
	"CURRENT_PRICE"	NUMERIC DEFAULT 1,
	"CURRENCY"	TEXT,
	"INITIAL_DATE"	TEXT,
	"PRICE_SOURCE"	TEXT,
	PRIMARY KEY("ASSET_ID")
)