CREATE TABLE IF NOT EXISTS "PORTFOLIO_PROFILE_TARGETS" (
    "PORTFOLIO_ID" INTEGER NOT NULL,
    "PROFILE" TEXT NOT NULL,
    "TARGET_PERCENTAGE" REAL NOT NULL,
    PRIMARY KEY("PORTFOLIO_ID", "PROFILE"),
    FOREIGN KEY("PORTFOLIO_ID") REFERENCES "PORTFOLIOS"("PORTFOLIO_ID") ON DELETE CASCADE
);