CREATE TABLE IF NOT EXISTS "PORTFOLIOS" (
    "PORTFOLIO_ID" INTEGER,
    "OWNER_ID" INTEGER,
    "NAME" TEXT NOT NULL,
    "CURRENCY" TEXT DEFAULT 'PLN',
    "IS_ALL_HOLDINGS" INTEGER DEFAULT 0,
    PRIMARY KEY("PORTFOLIO_ID"),
    FOREIGN KEY("OWNER_ID") REFERENCES "ACCOUNT_OWNERS"("ACCOUNT_OWNER_ID"),
    UNIQUE("OWNER_ID", "NAME")
);
