CREATE TABLE IF NOT EXISTS "AGGREGATED_VALUES" (
    "TIMESTAMP" TIMESTAMP,
    "ASSET_ID" INTEGER,
    "PORTFOLIO_ID" INTEGER,
    "AGGREGATED_VALUE" REAL,
    PRIMARY KEY("TIMESTAMP", "ASSET_ID", "PORTFOLIO_ID"),
    FOREIGN KEY("PORTFOLIO_ID") REFERENCES "PORTFOLIOS"("PORTFOLIO_ID")
);
