CREATE TABLE IF NOT EXISTS "AGGREGATED_VALUES" (
	"TIMESTAMP"	TIMESTAMP,
	"ASSET_ID"	INTEGER,
	"ACCOUNT_OWNER_ID"	TEXT,
	"AGGREGATED_VALUE"	REAL,
	PRIMARY KEY("TIMESTAMP","ASSET_ID","ACCOUNT_OWNER_ID")
)