CREATE TABLE IF NOT EXISTS "MAPPING_PORTFOLIOS" (
    "PORTFOLIO_ID" INTEGER NOT NULL,
    "ASSET_ID" INTEGER NOT NULL,
    "ACCOUNT_ID" TEXT NOT NULL,
    "TARGET_ALLOCATION" REAL,
    PRIMARY KEY("PORTFOLIO_ID", "ASSET_ID", "ACCOUNT_ID"),
    FOREIGN KEY("PORTFOLIO_ID") REFERENCES "PORTFOLIOS"("PORTFOLIO_ID") ON DELETE CASCADE,
    FOREIGN KEY("ASSET_ID") REFERENCES "ASSETS"("ASSET_ID"),
    FOREIGN KEY("ACCOUNT_ID") REFERENCES "ACCOUNTS"("ACCOUNT_ID")
);
