DROP VIEW IF EXISTS V_PORTFOLIO_TRANSACTIONS;

CREATE VIEW V_PORTFOLIO_TRANSACTIONS AS
SELECT
    p.PORTFOLIO_ID,
    p.OWNER_ID AS PORTFOLIO_OWNER_ID,
    a.ACCOUNT_ID,
    a.ACCOUNT_NAME,
    t.TIMESTAMP,
    t.ASSET_ID,
    y.YFINANCE_ID,
    COALESCE(y.PRICE_MULTIPLIER, 1) AS PRICE_MULTIPLIER,
    t.BUY_SELL,
    t.VOLUME,
    t.PRICE,
    t.TRANSACTION_FEE,
    t.ASSET_CURRENCY,
    t.BASE_CURRENCY,
    t.FX_RATE
FROM PORTFOLIO_MEMBERSHIP m
JOIN PORTFOLIOS_V2 p
    ON p.PORTFOLIO_ID = m.PORTFOLIO_ID
JOIN ACCOUNTS_V2 a
    ON a.ACCOUNT_ID = m.ACCOUNT_ID
JOIN TRANSACTIONS t
    ON t.ACCOUNT_ID = m.ACCOUNT_ID
   AND (m.ASSET_ID IS NULL OR t.ASSET_ID = m.ASSET_ID)
LEFT JOIN MAPPING_YFINANCE y
    ON y.ASSET_ID = t.ASSET_ID
WHERE m.INCLUDED = 1
  AND p.IS_ACTIVE = 1
  AND a.IS_ACTIVE = 1
  AND (p.OWNER_ID = 0 OR p.OWNER_ID = a.OWNER_ID);
