DROP VIEW IF EXISTS V_PORTFOLIO_HOLDINGS;

CREATE VIEW V_PORTFOLIO_HOLDINGS AS
SELECT
    p.PORTFOLIO_ID,
    p.OWNER_ID AS PORTFOLIO_OWNER_ID,
    m.ACCOUNT_ID,
    a.ACCOUNT_NAME,
    h.ASSET_ID,
    h.VOLUME,
    h.REFRESH_DATE
FROM PORTFOLIO_MEMBERSHIP m
JOIN PORTFOLIOS_V2 p
    ON p.PORTFOLIO_ID = m.PORTFOLIO_ID
JOIN ACCOUNTS_V2 a
    ON a.ACCOUNT_ID = m.ACCOUNT_ID
JOIN HOLDINGS h
    ON h.ACCOUNT_ID = m.ACCOUNT_ID
   AND (m.ASSET_ID IS NULL OR h.ASSET_ID = m.ASSET_ID)
WHERE m.INCLUDED = 1
  AND p.IS_ACTIVE = 1
  AND a.IS_ACTIVE = 1
  AND (p.OWNER_ID = 0 OR p.OWNER_ID = a.OWNER_ID);
