DROP VIEW IF EXISTS TRANSACTIONS_ALL;

CREATE VIEW TRANSACTIONS_ALL AS

SELECT
        a.ACCOUNT_OWNER,
        a.ACCOUNT_ID,
        a.ACCOUNT_NAME,
        t.TIMESTAMP,
        t.ASSET_ID,
        y.YFINANCE_ID,
        COALESCE(y.PRICE_MULTIPLIER, 1) AS PRICE_MULTIPLIER,
        t.BUY_SELL,
        t.VOLUME,
        t.PRICE,
        t.TRANSACTION_FEE,
        t.ASSET_CURRENCY,
        t.BASE_CURRENCY,
        t.FX_RATE

FROM
    ACCOUNTS a
LEFT JOIN
    TRANSACTIONS t ON a.ACCOUNT_ID = t.ACCOUNT_ID
LEFT JOIN
    ASSETS s ON t.ASSET_ID = s.ASSET_ID
LEFT JOIN
    MAPPING_YFINANCE y ON t.ASSET_ID = y.ASSET_ID
WHERE
    1=1

