DROP VIEW IF EXISTS V_PORTFOLIO_DRIFT;

CREATE VIEW V_PORTFOLIO_DRIFT AS
WITH target_rows AS (
    SELECT
        p.PORTFOLIO_ID,
        t.TARGET_LEVEL,
        t.TARGET_KEY,
        t.TARGET_WEIGHT
    FROM PORTFOLIOS_V2 p
    JOIN PORTFOLIO_PROFILE_TARGETS t
      ON t.PROFILE_ID = p.TARGET_PROFILE_ID
),
actual_rows AS (
    SELECT
        PORTFOLIO_ID,
        'CATEGORY' AS TARGET_LEVEL,
        CATEGORY AS TARGET_KEY,
        SUM(CURRENT_ASSET_VALUE) AS CURRENT_VALUE
    FROM V_PORTFOLIO_CURRENT_VALUES
    GROUP BY PORTFOLIO_ID, CATEGORY

    UNION ALL

    SELECT
        PORTFOLIO_ID,
        'SUB_CATEGORY' AS TARGET_LEVEL,
        SUB_CATEGORY AS TARGET_KEY,
        SUM(CURRENT_ASSET_VALUE) AS CURRENT_VALUE
    FROM V_PORTFOLIO_CURRENT_VALUES
    GROUP BY PORTFOLIO_ID, SUB_CATEGORY

    UNION ALL

    SELECT
        PORTFOLIO_ID,
        'ASSET' AS TARGET_LEVEL,
        CAST(ASSET_ID AS TEXT) AS TARGET_KEY,
        SUM(CURRENT_ASSET_VALUE) AS CURRENT_VALUE
    FROM V_PORTFOLIO_CURRENT_VALUES
    GROUP BY PORTFOLIO_ID, ASSET_ID
),
portfolio_totals AS (
    SELECT
        PORTFOLIO_ID,
        SUM(CURRENT_ASSET_VALUE) AS TOTAL_VALUE
    FROM V_PORTFOLIO_CURRENT_VALUES
    GROUP BY PORTFOLIO_ID
)
SELECT
    t.PORTFOLIO_ID,
    t.TARGET_LEVEL,
    t.TARGET_KEY,
    t.TARGET_WEIGHT,
    COALESCE(a.CURRENT_VALUE, 0) AS CURRENT_VALUE,
    CASE
        WHEN COALESCE(pt.TOTAL_VALUE, 0) = 0 THEN 0
        ELSE COALESCE(a.CURRENT_VALUE, 0) / pt.TOTAL_VALUE
    END AS CURRENT_WEIGHT,
    (CASE
        WHEN COALESCE(pt.TOTAL_VALUE, 0) = 0 THEN 0
        ELSE COALESCE(a.CURRENT_VALUE, 0) / pt.TOTAL_VALUE
    END - t.TARGET_WEIGHT) AS WEIGHT_DRIFT
FROM target_rows t
LEFT JOIN actual_rows a
       ON a.PORTFOLIO_ID = t.PORTFOLIO_ID
      AND a.TARGET_LEVEL = t.TARGET_LEVEL
      AND a.TARGET_KEY = t.TARGET_KEY
LEFT JOIN portfolio_totals pt
       ON pt.PORTFOLIO_ID = t.PORTFOLIO_ID;
