DROP VIEW IF EXISTS "main"."TRANSACTIONS_ALL";
CREATE VIEW TRANSACTIONS_ALL AS
SELECT
    p.PORTFOLIO_ID,
    p.NAME AS PORTFOLIO_NAME,
    a.ACCOUNT_OWNER_ID,
    a.ACCOUNT_ID,
    a.ACCOUNT_NAME,
    t.TIMESTAMP,
    t.ASSET_ID,
    y.YFINANCE_ID,
    COALESCE(y.PRICE_MULTIPLIER, 1) AS PRICE_MULTIPLIER,
    t.BUY_SELL,
    t.VOLUME,
    t.PRICE,
    t.TRANSACTION_FEE,
    t.ASSET_CURRENCY,
    t.BASE_CURRENCY,
    t.FX_RATE
FROM TRANSACTIONS t
JOIN ACCOUNTS a ON a.ACCOUNT_ID = t.ACCOUNT_ID
JOIN PORTFOLIOS p
    ON (p.OWNER_ID = a.ACCOUNT_OWNER_ID OR p.IS_ALL_HOLDINGS = 1)
LEFT JOIN MAPPING_PORTFOLIOS mp
    ON mp.PORTFOLIO_ID = p.PORTFOLIO_ID
    AND mp.ACCOUNT_ID = t.ACCOUNT_ID
    AND mp.ASSET_ID = t.ASSET_ID
LEFT JOIN MAPPING_YFINANCE y ON t.ASSET_ID = y.ASSET_ID
WHERE p.IS_ALL_HOLDINGS = 1 OR mp.PORTFOLIO_ID IS NOT NULL;