DROP VIEW IF EXISTS V_PORTFOLIO_ALLOCATION;

CREATE VIEW V_PORTFOLIO_ALLOCATION AS
WITH agg AS (
    SELECT
        PORTFOLIO_ID,
        CATEGORY,
        SUB_CATEGORY,
        PROFILE,
        SUM(CURRENT_ASSET_VALUE) AS CURRENT_ASSET_VALUE
    FROM V_PORTFOLIO_CURRENT_VALUES
    GROUP BY PORTFOLIO_ID, CATEGORY, SUB_CATEGORY, PROFILE
),
totals AS (
    SELECT
        PORTFOLIO_ID,
        SUM(CURRENT_ASSET_VALUE) AS TOTAL_VALUE
    FROM agg
    GROUP BY PORTFOLIO_ID
)
SELECT
    a.PORTFOLIO_ID,
    a.CATEGORY,
    a.SUB_CATEGORY,
    a.PROFILE,
    a.CURRENT_ASSET_VALUE,
    CASE
        WHEN t.TOTAL_VALUE = 0 THEN 0
        ELSE a.CURRENT_ASSET_VALUE / t.TOTAL_VALUE
    END AS CURRENT_WEIGHT
FROM agg a
JOIN totals t
  ON t.PORTFOLIO_ID = a.PORTFOLIO_ID;
