DROP VIEW IF EXISTS HOLDINGS;

CREATE VIEW HOLDINGS AS
SELECT
    ASSET_ID,
    ACCOUNT_ID,
    SUM(CASE
            WHEN BUY_SELL = 'B' THEN VOLUME
            WHEN BUY_SELL = 'S' THEN -VOLUME
            ELSE 0
        END) AS VOLUME,
    MAX(TIMESTAMP) AS REFRESH_DATE
FROM
    TRANSACTIONS
GROUP BY
    ASSET_ID,
    ACCOUNT_ID
HAVING
    SUM(CASE
            WHEN BUY_SELL = 'B' THEN VOLUME
            WHEN BUY_SELL = 'S' THEN -VOLUME
            ELSE 0
        END) > 0;