DROP VIEW IF EXISTS "main"."AGGREGATED_PORTFOLIO_VALUES";
CREATE VIEW AGGREGATED_PORTFOLIO_VALUES AS
SELECT
    av.TIMESTAMP,
    av.PORTFOLIO_ID,
    p.NAME AS PORTFOLIO_NAME,
    a.SUB_CATEGORY,
    SUM(av.AGGREGATED_VALUE) AS AGGREGATED_VALUE
FROM AGGREGATED_VALUES av
JOIN ASSETS a ON av.ASSET_ID = a.ASSET_ID
JOIN PORTFOLIOS p ON av.PORTFOLIO_ID = p.PORTFOLIO_ID
GROUP BY av.TIMESTAMP, av.PORTFOLIO_ID, p.NAME, a.SUB_CATEGORY
ORDER BY av.TIMESTAMP, av.PORTFOLIO_ID, a.SUB_CATEGORY;