DROP VIEW IF EXISTS "main"."CURRENT_HOLDINGS_ALL";
CREATE VIEW CURRENT_HOLDINGS_ALL AS
SELECT
    p.PORTFOLIO_ID,
    p.NAME AS PORTFOLIO_NAME,
    a.ACCOUNT_OWNER_ID,
    h.ACCOUNT_ID,
    a.ACCOUNT_NAME,
    h.ASSET_ID,
    h.VOLUME,
    s.NAME,
    s.MARKET,
    s.CATEGORY,
    s.SUB_CATEGORY,
    s.PROFILE,
    mp.TARGET_ALLOCATION,
    pr.PRICE AS CURRENT_PRICE,
    s.CURRENCY,
    CAST(COALESCE(c.PRICE, 1) AS REAL) AS FX_RATE
FROM HOLDINGS h
JOIN ACCOUNTS a ON h.ACCOUNT_ID = a.ACCOUNT_ID
JOIN PORTFOLIOS p
    ON (p.OWNER_ID = a.ACCOUNT_OWNER_ID OR p.IS_ALL_HOLDINGS = 1)
LEFT JOIN MAPPING_PORTFOLIOS mp
    ON mp.PORTFOLIO_ID = p.PORTFOLIO_ID
    AND mp.ACCOUNT_ID = h.ACCOUNT_ID
    AND mp.ASSET_ID = h.ASSET_ID
LEFT JOIN ASSETS s ON h.ASSET_ID = s.ASSET_ID
LEFT JOIN LATEST_PRICES pr ON s.ASSET_ID = pr.ASSET_ID
LEFT JOIN (
    SELECT lc.PRICE, s2.CURRENCY
    FROM LATEST_CURRENCIES lc
    JOIN ASSETS s2 ON lc.ASSET_ID = s2.ASSET_ID
) c ON s.CURRENCY = c.CURRENCY
WHERE p.IS_ALL_HOLDINGS = 1 OR mp.PORTFOLIO_ID IS NOT NULL;