DROP VIEW IF EXISTS V_PORTFOLIO_CURRENT_VALUES;

CREATE VIEW V_PORTFOLIO_CURRENT_VALUES AS
SELECT
    ph.PORTFOLIO_ID,
    ph.PORTFOLIO_OWNER_ID,
    ph.ACCOUNT_ID,
    ph.ACCOUNT_NAME,
    ph.ASSET_ID,
    s.NAME AS ASSET_NAME,
    s.CATEGORY,
    s.SUB_CATEGORY,
    s.PROFILE,
    s.CURRENCY,
    ph.VOLUME,
    COALESCE(lp.PRICE, 0) AS CURRENT_PRICE,
    COALESCE(fx.PRICE, 1) AS FX_RATE,
    (ph.VOLUME * COALESCE(lp.PRICE, 0) * COALESCE(fx.PRICE, 1)) AS CURRENT_ASSET_VALUE,
    ph.REFRESH_DATE
FROM V_PORTFOLIO_HOLDINGS ph
LEFT JOIN ASSETS s
    ON s.ASSET_ID = ph.ASSET_ID
LEFT JOIN LATEST_PRICES lp
    ON lp.ASSET_ID = ph.ASSET_ID
LEFT JOIN (
    SELECT
        a.CURRENCY,
        c.PRICE
    FROM LATEST_CURRENCIES c
    JOIN ASSETS a ON a.ASSET_ID = c.ASSET_ID
) fx
    ON fx.CURRENCY = s.CURRENCY;
