-- Portfolio-centric redesign migration blueprint (SQLite)
-- Intentionally additive-first so it can be applied on existing DB before cleanup.

PRAGMA foreign_keys = ON;

BEGIN TRANSACTION;

-- 1) Owners
CREATE TABLE IF NOT EXISTS OWNERS (
    OWNER_ID INTEGER PRIMARY KEY,
    OWNER_CODE TEXT NOT NULL UNIQUE,
    OWNER_NAME TEXT NOT NULL,
    IS_ADMIN_SCOPE INTEGER NOT NULL DEFAULT 0 CHECK (IS_ADMIN_SCOPE IN (0,1)),
    IS_ACTIVE INTEGER NOT NULL DEFAULT 1 CHECK (IS_ACTIVE IN (0,1))
);

-- 2) New accounts table with explicit FK (kept separate to avoid destructive ALTER patterns in SQLite)
CREATE TABLE IF NOT EXISTS ACCOUNTS_V2 (
    ACCOUNT_ID TEXT PRIMARY KEY,
    ACCOUNT_NAME TEXT NOT NULL,
    OWNER_ID INTEGER NOT NULL,
    BROKER TEXT,
    IS_ACTIVE INTEGER NOT NULL DEFAULT 1 CHECK (IS_ACTIVE IN (0,1)),
    FOREIGN KEY (OWNER_ID) REFERENCES OWNERS (OWNER_ID)
);

-- 3) Portfolios
CREATE TABLE IF NOT EXISTS PORTFOLIO_PROFILES (
    PROFILE_ID INTEGER PRIMARY KEY,
    PROFILE_NAME TEXT NOT NULL UNIQUE,
    DESCRIPTION TEXT,
    IS_ACTIVE INTEGER NOT NULL DEFAULT 1 CHECK (IS_ACTIVE IN (0,1))
);

CREATE TABLE IF NOT EXISTS PORTFOLIOS_V2 (
    PORTFOLIO_ID INTEGER PRIMARY KEY,
    OWNER_ID INTEGER NOT NULL,
    PORTFOLIO_CODE TEXT NOT NULL UNIQUE,
    PORTFOLIO_NAME TEXT NOT NULL,
    BASE_CURRENCY TEXT NOT NULL DEFAULT 'PLN',
    TARGET_PROFILE_ID INTEGER,
    IS_DEFAULT INTEGER NOT NULL DEFAULT 0 CHECK (IS_DEFAULT IN (0,1)),
    IS_ACTIVE INTEGER NOT NULL DEFAULT 1 CHECK (IS_ACTIVE IN (0,1)),
    FOREIGN KEY (OWNER_ID) REFERENCES OWNERS (OWNER_ID),
    FOREIGN KEY (TARGET_PROFILE_ID) REFERENCES PORTFOLIO_PROFILES (PROFILE_ID)
);

CREATE TABLE IF NOT EXISTS PORTFOLIO_PROFILE_TARGETS (
    PROFILE_ID INTEGER NOT NULL,
    TARGET_LEVEL TEXT NOT NULL CHECK (TARGET_LEVEL IN ('CATEGORY', 'SUB_CATEGORY', 'ASSET')),
    TARGET_KEY TEXT NOT NULL,
    TARGET_WEIGHT REAL NOT NULL CHECK (TARGET_WEIGHT >= 0 AND TARGET_WEIGHT <= 1),
    PRIMARY KEY (PROFILE_ID, TARGET_LEVEL, TARGET_KEY),
    FOREIGN KEY (PROFILE_ID) REFERENCES PORTFOLIO_PROFILES (PROFILE_ID)
);

-- 4) Portfolio membership
CREATE TABLE IF NOT EXISTS PORTFOLIO_MEMBERSHIP (
    PORTFOLIO_ID INTEGER NOT NULL,
    ACCOUNT_ID TEXT NOT NULL,
    ASSET_ID INTEGER,
    INCLUDED INTEGER NOT NULL DEFAULT 1 CHECK (INCLUDED IN (0,1)),
    PRIMARY KEY (PORTFOLIO_ID, ACCOUNT_ID, ASSET_ID),
    FOREIGN KEY (PORTFOLIO_ID) REFERENCES PORTFOLIOS_V2 (PORTFOLIO_ID),
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS_V2 (ACCOUNT_ID),
    FOREIGN KEY (ASSET_ID) REFERENCES ASSETS (ASSET_ID)
);

-- Seed `ALL` owner (id = 0) for global scope
INSERT OR IGNORE INTO OWNERS (OWNER_ID, OWNER_CODE, OWNER_NAME, IS_ADMIN_SCOPE)
VALUES (0, 'ALL', 'All Holdings', 1);

-- Optional bootstrap from legacy table names if present
INSERT OR IGNORE INTO OWNERS (OWNER_ID, OWNER_CODE, OWNER_NAME, IS_ADMIN_SCOPE)
SELECT CAST(ACCOUNT_OWNER_ID AS INTEGER),
       'OWNER_' || ACCOUNT_OWNER_ID,
       ACCOUNT_OWNER_NAME,
       0
FROM ACCOUNT_OWNERS
WHERE ACCOUNT_OWNER_ID IS NOT NULL;

INSERT OR IGNORE INTO ACCOUNTS_V2 (ACCOUNT_ID, ACCOUNT_NAME, OWNER_ID, BROKER)
SELECT ACCOUNT_ID,
       ACCOUNT_NAME,
       CAST(ACCOUNT_OWNER_ID AS INTEGER),
       BROKER
FROM ACCOUNTS;

-- Create one default portfolio per owner
INSERT OR IGNORE INTO PORTFOLIOS_V2 (PORTFOLIO_ID, OWNER_ID, PORTFOLIO_CODE, PORTFOLIO_NAME, IS_DEFAULT)
SELECT OWNER_ID + 1000,
       OWNER_ID,
       'P_DEFAULT_' || OWNER_ID,
       'Default Portfolio - ' || OWNER_NAME,
       1
FROM OWNERS;

-- Add full-account membership into default portfolios (ASSET_ID = NULL => all assets)
INSERT OR IGNORE INTO PORTFOLIO_MEMBERSHIP (PORTFOLIO_ID, ACCOUNT_ID, ASSET_ID)
SELECT p.PORTFOLIO_ID,
       a.ACCOUNT_ID,
       NULL
FROM PORTFOLIOS_V2 p
JOIN ACCOUNTS_V2 a ON a.OWNER_ID = p.OWNER_ID
WHERE p.IS_DEFAULT = 1;

COMMIT;
