-- Migration proposal: move filtering dimension from ACCOUNT_OWNER_ID to PORTFOLIO_ID
-- Safe to run after taking a DB backup.

PRAGMA foreign_keys = ON;

BEGIN TRANSACTION;

-- 1) Portfolio master (if existing table is too small, recreate via rename)
CREATE TABLE IF NOT EXISTS PORTFOLIOS_NEW (
    PORTFOLIO_ID     INTEGER PRIMARY KEY,
    PORTFOLIO_CODE   TEXT NOT NULL UNIQUE,
    PORTFOLIO_NAME   TEXT NOT NULL,
    BASE_CURRENCY    TEXT NOT NULL DEFAULT 'PLN',
    IS_ACTIVE        INTEGER NOT NULL DEFAULT 1,
    CREATED_AT       TEXT NOT NULL DEFAULT (datetime('now')),
    UPDATED_AT       TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Keep existing rows if old PORTFOLIOS exists and has basic fields.
INSERT INTO PORTFOLIOS_NEW (PORTFOLIO_ID, PORTFOLIO_CODE, PORTFOLIO_NAME, BASE_CURRENCY)
SELECT PORTFOLIO_ID,
       COALESCE(CAST(PORTFOLIO_ID AS TEXT), 'P' || PORTFOLIO_ID),
       COALESCE(NAME, 'Portfolio ' || PORTFOLIO_ID),
       COALESCE(CURRENCY, 'PLN')
FROM PORTFOLIOS
WHERE NOT EXISTS (
    SELECT 1
    FROM PORTFOLIOS_NEW p
    WHERE p.PORTFOLIO_ID = PORTFOLIOS.PORTFOLIO_ID
);

DROP TABLE IF EXISTS PORTFOLIOS;
ALTER TABLE PORTFOLIOS_NEW RENAME TO PORTFOLIOS;

-- 2) Which accounts / account-assets belong to a portfolio.
--    If ASSET_ID is NULL => whole account included.
--    If ASSET_ID is NOT NULL => only that instrument from that account included.
CREATE TABLE IF NOT EXISTS PORTFOLIO_MEMBERS (
    PORTFOLIO_MEMBER_ID INTEGER PRIMARY KEY,
    PORTFOLIO_ID        INTEGER NOT NULL,
    ACCOUNT_ID          TEXT NOT NULL,
    ASSET_ID            INTEGER,
    INCLUSION_PCT       REAL NOT NULL DEFAULT 100.0 CHECK (INCLUSION_PCT >= 0 AND INCLUSION_PCT <= 100),
    EFFECTIVE_FROM      TEXT NOT NULL DEFAULT '1900-01-01',
    EFFECTIVE_TO        TEXT,
    FOREIGN KEY (PORTFOLIO_ID) REFERENCES PORTFOLIOS(PORTFOLIO_ID)
);

-- Uniqueness of mapping rules: separate indexes for whole-account vs account+asset rules.
CREATE UNIQUE INDEX IF NOT EXISTS UX_PORTFOLIO_MEMBERS_ACCOUNT
    ON PORTFOLIO_MEMBERS (PORTFOLIO_ID, ACCOUNT_ID, EFFECTIVE_FROM)
    WHERE ASSET_ID IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS UX_PORTFOLIO_MEMBERS_ASSET
    ON PORTFOLIO_MEMBERS (PORTFOLIO_ID, ACCOUNT_ID, ASSET_ID, EFFECTIVE_FROM)
    WHERE ASSET_ID IS NOT NULL;

CREATE INDEX IF NOT EXISTS IX_PORTFOLIO_MEMBERS_P ON PORTFOLIO_MEMBERS (PORTFOLIO_ID);
CREATE INDEX IF NOT EXISTS IX_PORTFOLIO_MEMBERS_ACC ON PORTFOLIO_MEMBERS (ACCOUNT_ID);
CREATE INDEX IF NOT EXISTS IX_PORTFOLIO_MEMBERS_ASSET ON PORTFOLIO_MEMBERS (ASSET_ID);

-- 3) Optional relation: owners linked to portfolios (for permissions/UI grouping)
CREATE TABLE IF NOT EXISTS PORTFOLIO_OWNERS (
    PORTFOLIO_ID       INTEGER NOT NULL,
    ACCOUNT_OWNER_ID   INTEGER NOT NULL,
    PRIMARY KEY (PORTFOLIO_ID, ACCOUNT_OWNER_ID),
    FOREIGN KEY (PORTFOLIO_ID) REFERENCES PORTFOLIOS(PORTFOLIO_ID)
);

-- 4) Target profile allocation for drift comparison (must sum to 100 per portfolio)
CREATE TABLE IF NOT EXISTS PORTFOLIO_TARGET_PROFILE (
    PORTFOLIO_ID        INTEGER NOT NULL,
    PROFILE             TEXT NOT NULL,
    TARGET_PCT          REAL NOT NULL CHECK (TARGET_PCT >= 0 AND TARGET_PCT <= 100),
    PRIMARY KEY (PORTFOLIO_ID, PROFILE),
    FOREIGN KEY (PORTFOLIO_ID) REFERENCES PORTFOLIOS(PORTFOLIO_ID)
);

CREATE INDEX IF NOT EXISTS IX_PORTFOLIO_TARGET_PROFILE_P ON PORTFOLIO_TARGET_PROFILE (PORTFOLIO_ID);

CREATE TRIGGER IF NOT EXISTS TRG_PORTFOLIO_TARGET_PROFILE_SUM_INS
AFTER INSERT ON PORTFOLIO_TARGET_PROFILE
BEGIN
    SELECT CASE
        WHEN (SELECT COALESCE(SUM(TARGET_PCT), 0)
              FROM PORTFOLIO_TARGET_PROFILE
              WHERE PORTFOLIO_ID = NEW.PORTFOLIO_ID) > 100.0001
        THEN RAISE(ABORT, 'Target profile weights cannot exceed 100% per portfolio')
    END;
END;

CREATE TRIGGER IF NOT EXISTS TRG_PORTFOLIO_TARGET_PROFILE_SUM_UPD
AFTER UPDATE ON PORTFOLIO_TARGET_PROFILE
BEGIN
    SELECT CASE
        WHEN (SELECT COALESCE(SUM(TARGET_PCT), 0)
              FROM PORTFOLIO_TARGET_PROFILE
              WHERE PORTFOLIO_ID = NEW.PORTFOLIO_ID) > 100.0001
        THEN RAISE(ABORT, 'Target profile weights cannot exceed 100% per portfolio')
    END;
END;

-- 5) Seed portfolios from existing ACCOUNT_OWNER_ID model
INSERT INTO PORTFOLIOS (PORTFOLIO_CODE, PORTFOLIO_NAME, BASE_CURRENCY)
SELECT DISTINCT
       'OWNER_' || CAST(a.ACCOUNT_OWNER_ID AS TEXT) AS PORTFOLIO_CODE,
       'Owner ' || CAST(a.ACCOUNT_OWNER_ID AS TEXT) AS PORTFOLIO_NAME,
       'PLN'
FROM ACCOUNTS a
WHERE a.ACCOUNT_OWNER_ID IS NOT NULL
  AND NOT EXISTS (
      SELECT 1
      FROM PORTFOLIOS p
      WHERE p.PORTFOLIO_CODE = 'OWNER_' || CAST(a.ACCOUNT_OWNER_ID AS TEXT)
  );

INSERT INTO PORTFOLIO_OWNERS (PORTFOLIO_ID, ACCOUNT_OWNER_ID)
SELECT p.PORTFOLIO_ID, CAST(a.ACCOUNT_OWNER_ID AS INTEGER)
FROM ACCOUNTS a
JOIN PORTFOLIOS p ON p.PORTFOLIO_CODE = 'OWNER_' || CAST(a.ACCOUNT_OWNER_ID AS TEXT)
GROUP BY p.PORTFOLIO_ID, CAST(a.ACCOUNT_OWNER_ID AS INTEGER);

INSERT INTO PORTFOLIO_MEMBERS (PORTFOLIO_ID, ACCOUNT_ID, ASSET_ID, INCLUSION_PCT)
SELECT p.PORTFOLIO_ID, a.ACCOUNT_ID, NULL, 100.0
FROM ACCOUNTS a
JOIN PORTFOLIOS p ON p.PORTFOLIO_CODE = 'OWNER_' || CAST(a.ACCOUNT_OWNER_ID AS TEXT)
WHERE NOT EXISTS (
    SELECT 1 FROM PORTFOLIO_MEMBERS m
    WHERE m.PORTFOLIO_ID = p.PORTFOLIO_ID
      AND m.ACCOUNT_ID = a.ACCOUNT_ID
      AND m.ASSET_ID IS NULL
      AND m.EFFECTIVE_FROM = '1900-01-01'
);

-- Optional global portfolio replacing ad-hoc 'None'.
INSERT INTO PORTFOLIOS (PORTFOLIO_CODE, PORTFOLIO_NAME, BASE_CURRENCY)
SELECT 'ALL', 'All portfolios', 'PLN'
WHERE NOT EXISTS (SELECT 1 FROM PORTFOLIOS WHERE PORTFOLIO_CODE = 'ALL');

INSERT INTO PORTFOLIO_MEMBERS (PORTFOLIO_ID, ACCOUNT_ID, ASSET_ID, INCLUSION_PCT)
SELECT p.PORTFOLIO_ID, a.ACCOUNT_ID, NULL, 100.0
FROM ACCOUNTS a
JOIN PORTFOLIOS p ON p.PORTFOLIO_CODE = 'ALL'
WHERE NOT EXISTS (
    SELECT 1 FROM PORTFOLIO_MEMBERS m
    WHERE m.PORTFOLIO_ID = p.PORTFOLIO_ID
      AND m.ACCOUNT_ID = a.ACCOUNT_ID
      AND m.ASSET_ID IS NULL
      AND m.EFFECTIVE_FROM = '1900-01-01'
);

COMMIT;

-- 6) New portfolio-centric views (keep old owner-centric views for backward compatibility)
DROP VIEW IF EXISTS PORTFOLIO_TRANSACTIONS_ALL;
CREATE VIEW PORTFOLIO_TRANSACTIONS_ALL AS
SELECT
    pm.PORTFOLIO_ID,
    t.ACCOUNT_ID,
    a.ACCOUNT_NAME,
    t.TIMESTAMP,
    t.ASSET_ID,
    t.BUY_SELL,
    t.VOLUME * (pm.INCLUSION_PCT / 100.0) AS VOLUME,
    t.PRICE,
    t.TRANSACTION_FEE * (pm.INCLUSION_PCT / 100.0) AS TRANSACTION_FEE,
    t.ASSET_CURRENCY,
    t.BASE_CURRENCY,
    t.FX_RATE
FROM TRANSACTIONS t
JOIN ACCOUNTS a ON a.ACCOUNT_ID = t.ACCOUNT_ID
JOIN PORTFOLIO_MEMBERS pm
  ON pm.ACCOUNT_ID = t.ACCOUNT_ID
 AND (pm.ASSET_ID IS NULL OR pm.ASSET_ID = t.ASSET_ID)
 AND date(t.TIMESTAMP) >= date(pm.EFFECTIVE_FROM)
 AND (pm.EFFECTIVE_TO IS NULL OR date(t.TIMESTAMP) <= date(pm.EFFECTIVE_TO));

DROP VIEW IF EXISTS PORTFOLIO_CURRENT_HOLDINGS_ALL;
CREATE VIEW PORTFOLIO_CURRENT_HOLDINGS_ALL AS
WITH base AS (
    SELECT
        pm.PORTFOLIO_ID,
        h.ACCOUNT_ID,
        h.ASSET_ID,
        h.VOLUME * (pm.INCLUSION_PCT / 100.0) AS VOLUME
    FROM HOLDINGS h
    JOIN PORTFOLIO_MEMBERS pm
      ON pm.ACCOUNT_ID = h.ACCOUNT_ID
     AND (pm.ASSET_ID IS NULL OR pm.ASSET_ID = h.ASSET_ID)
)
SELECT
    b.PORTFOLIO_ID,
    b.ACCOUNT_ID,
    a.ACCOUNT_NAME,
    b.ASSET_ID,
    b.VOLUME,
    s.NAME,
    s.MARKET,
    s.CATEGORY,
    s.SUB_CATEGORY,
    s.PROFILE,
    p.PRICE AS CURRENT_PRICE,
    s.CURRENCY,
    CAST(COALESCE(c.PRICE, 1) AS REAL) AS FX_RATE
FROM base b
JOIN ACCOUNTS a ON b.ACCOUNT_ID = a.ACCOUNT_ID
LEFT JOIN ASSETS s ON b.ASSET_ID = s.ASSET_ID
LEFT JOIN LATEST_PRICES p ON s.ASSET_ID = p.ASSET_ID
LEFT JOIN (
    SELECT c.PRICE, s.CURRENCY
    FROM LATEST_CURRENCIES c
    JOIN ASSETS s ON c.ASSET_ID = s.ASSET_ID
) c ON s.CURRENCY = c.CURRENCY;

DROP VIEW IF EXISTS PORTFOLIO_PROFILE_DRIFT;
CREATE VIEW PORTFOLIO_PROFILE_DRIFT AS
WITH current_alloc AS (
    SELECT
        h.PORTFOLIO_ID,
        h.PROFILE,
        SUM(h.VOLUME * h.CURRENT_PRICE * h.FX_RATE) AS CURRENT_VALUE
    FROM PORTFOLIO_CURRENT_HOLDINGS_ALL h
    GROUP BY h.PORTFOLIO_ID, h.PROFILE
),
portfolio_totals AS (
    SELECT PORTFOLIO_ID, SUM(CURRENT_VALUE) AS TOTAL_VALUE
    FROM current_alloc
    GROUP BY PORTFOLIO_ID
)
SELECT
    c.PORTFOLIO_ID,
    c.PROFILE,
    ROUND(100.0 * c.CURRENT_VALUE / NULLIF(t.TOTAL_VALUE, 0), 4) AS CURRENT_PCT,
    tp.TARGET_PCT,
    ROUND((100.0 * c.CURRENT_VALUE / NULLIF(t.TOTAL_VALUE, 0)) - tp.TARGET_PCT, 4) AS DRIFT_PCT
FROM current_alloc c
JOIN portfolio_totals t ON t.PORTFOLIO_ID = c.PORTFOLIO_ID
LEFT JOIN PORTFOLIO_TARGET_PROFILE tp
  ON tp.PORTFOLIO_ID = c.PORTFOLIO_ID
 AND tp.PROFILE = c.PROFILE;
