PRAGMA foreign_keys = OFF;
BEGIN TRANSACTION;

DROP VIEW IF EXISTS AGGREGATED_PORTFOLIO_VALUES;
DROP VIEW IF EXISTS CURRENT_HOLDINGS_ALL;
DROP VIEW IF EXISTS TRANSACTIONS_ALL;

ALTER TABLE AGGREGATED_VALUES RENAME TO AGGREGATED_VALUES_OLD;
ALTER TABLE PORTFOLIOS RENAME TO PORTFOLIOS_OLD;
ALTER TABLE MAPPING_PORTFOLIOS RENAME TO MAPPING_PORTFOLIOS_OLD;

-- Rebuild tables with portfolio-first model
CREATE TABLE PORTFOLIOS (
    PORTFOLIO_ID INTEGER PRIMARY KEY,
    OWNER_ID INTEGER,
    NAME TEXT NOT NULL,
    CURRENCY TEXT DEFAULT 'PLN',
    IS_ALL_HOLDINGS INTEGER DEFAULT 0,
    FOREIGN KEY(OWNER_ID) REFERENCES ACCOUNT_OWNERS(ACCOUNT_OWNER_ID),
    UNIQUE(OWNER_ID, NAME)
);

CREATE TABLE MAPPING_PORTFOLIOS (
    PORTFOLIO_ID INTEGER NOT NULL,
    ASSET_ID INTEGER NOT NULL,
    ACCOUNT_ID TEXT NOT NULL,
    TARGET_ALLOCATION REAL,
    PRIMARY KEY(PORTFOLIO_ID, ASSET_ID, ACCOUNT_ID),
    FOREIGN KEY(PORTFOLIO_ID) REFERENCES PORTFOLIOS(PORTFOLIO_ID) ON DELETE CASCADE,
    FOREIGN KEY(ASSET_ID) REFERENCES ASSETS(ASSET_ID),
    FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNTS(ACCOUNT_ID)
);

CREATE TABLE AGGREGATED_VALUES (
    TIMESTAMP TIMESTAMP,
    ASSET_ID INTEGER,
    PORTFOLIO_ID INTEGER,
    AGGREGATED_VALUE REAL,
    PRIMARY KEY(TIMESTAMP, ASSET_ID, PORTFOLIO_ID),
    FOREIGN KEY(PORTFOLIO_ID) REFERENCES PORTFOLIOS(PORTFOLIO_ID)
);


CREATE TABLE PORTFOLIO_PROFILE_TARGETS (
    PORTFOLIO_ID INTEGER NOT NULL,
    PROFILE TEXT NOT NULL,
    TARGET_PERCENTAGE REAL NOT NULL,
    PRIMARY KEY(PORTFOLIO_ID, PROFILE),
    FOREIGN KEY(PORTFOLIO_ID) REFERENCES PORTFOLIOS(PORTFOLIO_ID) ON DELETE CASCADE
);

-- Seed one portfolio per owner and one global ALL portfolio
INSERT INTO PORTFOLIOS (PORTFOLIO_ID, OWNER_ID, NAME, CURRENCY, IS_ALL_HOLDINGS)
SELECT ACCOUNT_OWNER_ID, ACCOUNT_OWNER_ID, ACCOUNT_OWNER_NAME, 'PLN', 0
FROM ACCOUNT_OWNERS;

INSERT INTO PORTFOLIOS (OWNER_ID, NAME, CURRENCY, IS_ALL_HOLDINGS)
VALUES (NULL, 'ALL', 'PLN', 1);

-- Backfill mapping for owner portfolios from existing holdings
INSERT OR IGNORE INTO MAPPING_PORTFOLIOS (PORTFOLIO_ID, ASSET_ID, ACCOUNT_ID)
SELECT DISTINCT p.PORTFOLIO_ID, h.ASSET_ID, h.ACCOUNT_ID
FROM HOLDINGS h
JOIN ACCOUNTS a ON a.ACCOUNT_ID = h.ACCOUNT_ID
JOIN PORTFOLIOS p ON p.OWNER_ID = a.ACCOUNT_OWNER_ID AND p.IS_ALL_HOLDINGS = 0;

DROP TABLE AGGREGATED_VALUES_OLD;
DROP TABLE PORTFOLIOS_OLD;
DROP TABLE MAPPING_PORTFOLIOS_OLD;

COMMIT;
PRAGMA foreign_keys = ON;
