CREATE TABLE IF NOT EXISTS "TRANSACTIONS" (
	"TIMESTAMP"	TEXT,
	"ACCOUNT_ID"	INTEGER,
	"ASSET_ID"	INTEGER,
	"BUY_SELL"	TEXT,
	"VOLUME"	INTEGER,
	"PRICE"	REAL,
	"ASSET_CURRENCY"	TEXT,
	"TRANSACTION_FEE"	REAL,
	"BASE_CURRENCY"	TEXT,
	"FX_RATE"	REAL
)