CREATE TABLE IF NOT EXISTS "HOLDINGS" (
	"ASSET_ID"	INTEGER,
	"VOLUME"	INTEGER,
	"ACCOUNT_ID"	TEXT,
	"REFRESH_DATE"	TEXT,
	FOREIGN KEY("ASSET_ID") REFERENCES "ASSETS"("ASSET_ID"),
	FOREIGN KEY("ACCOUNT_ID") REFERENCES "ACCOUNTS"("ACCOUNT_ID")
)